### ISSUE TITLE
Feature request: line numbers

### ISSUE THREAD

**Issue by jellelicht** [kristoferbuffington/guile-pastebin#1]
Loving the ideas behind this project. It would be very nice to have line numbers in the pastes.
Even more useful would be to be able to directly link to a specific line number, e.g. [https://paste.freshbakedyams.com/paste/F7PMWGL0#L2](https://paste.freshbakedyams.com/paste/F7PMWGL0#L2) to link directly to line 2 of that specific paste.

**Comment by kristoferbuffington** [comment]
Great idea! 

Added in commit 86aa9b571f267095c7cd141048cd9bc08c0fdb06
