### ISSUE TITLE
Resource busy issue

### ISSUE THREAD

**Issue by amirouche** [kristoferbuffington/guile-pastebin#5]
On the guile mailing list, you wrote:

> I have noticed that I get "Resource busy" issues if multiple requests are handled by the server simultaneously. 

How can I reproduce the issue?

**Comment by amirouche** [comment]
I can't reproduce with the following simple bash program:

```sh
yes http://localhost:8080/paste/2233V7A1 | xargs  -P 10 -r -n 1 wget -nv --delete-after
```

**Comment by kristoferbuffington** [comment]
It is not possible to use two env simultaneously. Try ./scripts/pastebin -r to spawn a repl server and try executing queries from from it in geiser. I also tried to create a separate env for the repl, but that did not work either.

**Comment by kristoferbuffington** [comment]
It would be interesting to scale using NFS and have read-only and write-only nodes in the event this service has to handle a lot of traffic

**Comment by amirouche** [comment]
I figured you disabled fibers. I activated it, and added the revelant fix to make it work in parallel but the performance are very poor. I can not reproduce the issue on some other apps I have...

I will keep investigating.

**Comment by amirouche** [comment]
I don't know how to use geiser

**Comment by kristoferbuffington** [comment]
I start the server with ./scripts/pastebin --repl

The --repl argument spawns a repl server.

Connect to it through emacs with geiser like this
M-x geiser-connect

That will connect emacs to the running server. You should be able to redefine functions in the running process that way. The limitation is the request-handler passed to (run-server ...) cannot be changed without restarting the server.

**Comment by kristoferbuffington** [comment]
I intend to be able to handle all forms of files in the future like ptpb does. The standard guile (web server) is blocking, and serving up an image really lags the application as a result. When handling large files in a page with multiple request like images, the fibers web server is a considerable performance improvement, so hopefully that can happen soon!

I just picked up a copy of The Reasoned Schemer. Once I'm more informed about kanren I'll be more helpful on this front.

**Comment by amirouche** [comment]
personal backlog cleanup.
